#!/usr/bin/perl
use strict;
use warnings;
use File::Find;
use Path::Class;
use Getopt::Long;
use Data::Dumper;
use lib '.';
use FileModel;

# Cache of file ids and their full name
my @Fullname;

# Given an id, a filename-id and the parent-id,
# return a full filename for the file.
sub getFullFilename {
    my ( $id, $parentid, $filenameid ) = @_;

    # Get the filename associated with the $filenameid
    my $filename = dbGetFilename($filenameid) || 'ERR';

    # Get the full filename
    my $fullname = $Fullname[$parentid] . '/' . $filename;

    # Cache it for later
    $Fullname[$id] = $fullname;
    return ($fullname);
}

dbOpenDatabase();
$Fullname[0] = '';
my $id = 1;
while (1) {

    # 0   1       2       3      4
    # id,parent,filename,size,timestamp
    my (@row) = dbGetFile($id);
    $id++;
    last if ( !defined( $row[0] ) );
    my $tim = localtime( $row[4] );
    my $full = getFullFilename( $row[0], $row[1], $row[2] );

    printf( "%10d  %s  %s\n", $row[3], $tim, $full );
}
exit(0);
